version: "3.8"

services:
  api:
    build: .
    container_name: fastapi-app
    ports:
      - "8080:8000"
    depends_on:
      - db
    environment:
      DATABASE_URL: "mysql+asyncmy://user:password@db:3306/mydb"

  db:
    image: mysql:8.0.40
    container_name: mysql-db
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: mydb
      MYSQL_USER: user
      MYSQL_PASSWORD: password
    ports:
      - "3306:3306"
    volumes:
      - db_data:/var/lib/mysql

volumes:
  db_data:
